# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 503c0c683412e862d920632bb3baf0fbd674e0b0235777129a687a1a563c91b67cc93ef1bb5190eaf0aca1f92c79a980da7faed30d5fcb17ebd8454779523f65

test:
  secret_key_base: 8b6f32222f3cb25cac096456d41211bb6529fbb3acc8e7a3f6e330ace8f282000703dc9345bd78f4b04be6ab7327013088f8a8f15d0754617fe8902ce1ac54d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
